version: '3'
services:
 borgserver:
  restart: always
  image: martinbouillaud/borgbackup-server:latest
  volumes:
    - $HOME/dockers/borgbackup-server/backup:/backup
    - $HOME/dockers/borgbackup-server/sshkeys:/sshkeys
  ports:
    - "2222:22"
  environment:
    BORG_SERVE_ARGS: ""
    BORG_APPEND_ONLY: "no"
    BORG_ADMIN: ""
